# $Id: Makefile,v 1.3 2008/03/08 13:22:23 tho Exp $

include common.mk
include ../Makefile.conf

FILES = ../VERSION ../LICENSE ../Makefile
FILES_DIR = $(MAKL_ROOT)
FILES_MODE = 0444

include files.mk
