# $Id: Makefile,v 1.4 2008/11/07 20:00:50 tho Exp $

include common.mk
include ../Makefile.conf

FILES = ../VERSION ../LICENSE ../Makefile
FILES_DIR = "$(MAKL_ROOT)"
FILES_MODE = 0444

include files.mk
