# $Id: Makefile,v 1.2 2008/11/07 20:00:50 tho Exp $

include common.mk
include ../Makefile.conf

FILES = lorder mkdep.gcc.sh mkinstalldirs
FILES_DIR = $(MAKL_ROOT)/helpers
FILES_MODE = 0555

include files.mk
