include common.mk

XENO_NAME = ffmpeg

XENO_FETCH = svn checkout
XENO_FETCH_FLAGS = -r 7407
XENO_FETCH_URI = svn://svn.mplayerhq.hu/ffmpeg/trunk ffmpeg
XENO_FETCH_LOCAL = $(XENO_NAME)
XENO_FETCH_TREE = true

XENO_NO_UNZIP = true

XENO_PATCH_FILE = ffmpeg-rev7407.patch

include xeno.mk
