#
# $Id: Makefile,v 1.14 2006/11/16 16:53:34 tho Exp $
#

export MAKL_DIR := $(shell pwd)

-include etc/toolchain.mk
-include etc/map.mk
-include Makefile.conf

MAKL_VERSION = $(shell cat $(MAKL_DIR)/VERSION)
MAKLRC ?= $(MAKL_DIR)/makl.env
LOGIN_SHELL ?= bash

all help:
	@echo
	@echo "# MaKL version $(MAKL_VERSION) - (c) 2005-2006 - KoanLogic srl"
	@echo "Available targets:"
	@echo
	@echo "   * help        print this menu"
	@echo "   * hints       output environment variables"
	@echo "   * toolchain   install platform toolchain files"
	@echo "   * env         generate a file containing runtime MaKL variables"
	@echo "   * clean       remove autogenerated toolchain files"
	@echo
ifndef MAKL_DIR
	@echo "In order for MaKL to run properly, you must set the MAKL_DIR"
	@echo "environment variable.  Type 'make hints' to get an help."
	@echo
endif

toolchain:
	@setup/shlib_setup.sh $(MAKL_PLATFORM)
	@setup/toolchain_setup.sh $(MAKL_PLATFORM)

env:
	@setup/env_setup.sh $(MAKL_DIR) $(MAKL_VERSION) $(LOGIN_SHELL) \
        $(MAKLRC)
 
hints:
	@setup/shell_setup.sh $(MAKL_DIR)

install: toolchain Makefile.conf
	@$(MAKE) -I$(MAKL_DIR)/mk -C bin/ install
	@$(MKINSTALLDIRS) $(SHAREDIR)
	@for d in cf/ mk/ tc/ etc/ shlib/ helpers/ setup/ ; do  \
		cp -r $$d $(SHAREDIR)/$$d ;                         \
	done

uninstall: Makefile.conf
	@$(MAKE) -I$(MAKL_DIR)/mk -C bin/ uninstall
	@rm -rf $(SHAREDIR)

clean:
	rm -f $(MAKL_DIR)/etc/toolchain.mk
	rm -f $(MAKL_DIR)/etc/toolchain.cf
	rm -f $(MAKL_DIR)/mk/shlib.mk
	rm -f Makefile.conf conf.h
