# $Id: Makefile,v 1.7 2006/12/10 13:19:47 tho Exp $

include common.mk
include ../Makefile.conf

FILES = $(shell echo *.mk)
FILES_DIR = $(MAKL_ROOT)/mk
FILES_MODE = 0444

SUBDIR = priv

include files.mk
include subdir.mk
