# GNU and P Make compatible toolchain file.
# Autogenerated by MaKL - Fri Jul 29 14:08:03 CEST 2005
CC ?= cc
CFLAGS ?= -O -pipe
AR ?= ar
ARFLAGS ?= rl
RANLIB ?= ranlib
LD ?= ld 
LDFLAGS ?= 
MKDEP ?= mkdep
STRIP ?= strip
STRIP_FLAGS ?= -X
INSTALL ?= install
INSTALL_COPY ?= -c
INSTALL_STRIP ?= -s
