# $Id: Makefile,v 1.3 2008/10/09 20:58:01 tho Exp $

include common.mk
include ../../Makefile.conf

FILES = deps.mk funcs.mk obj.mk
FILES_DIR = $(MAKL_ROOT)/mk/priv
FILES_MODE = 0444

include files.mk
