# $Id: Makefile,v 1.4 2008/11/07 20:00:50 tho Exp $

include common.mk
include ../../Makefile.conf

FILES = deps.mk funcs.mk obj.mk
FILES_DIR = $(MAKL_ROOT)/mk/priv
FILES_MODE = 0444

include files.mk
