# $Id: Makefile,v 1.1 2006/12/09 22:42:10 tho Exp $

include common.mk
include ../../Makefile.conf

FILES = deps.mk funcs.mk shlib.mk
FILES_DIR = $(MAKL_ROOT)/mk/priv
FILES_MODE = 0444

include files.mk
