# $Id: Makefile,v 1.1 2006/12/09 22:42:10 tho Exp $

include common.mk
include ../../Makefile.conf

FILES = $(shell echo makl_*)
FILES_DIR = $(MAKL_ROOT)/cf/helpers
FILES_MODE = 0444

include files.mk
