# $Id: Makefile,v 1.2 2008/11/07 20:00:50 tho Exp $

include common.mk
include ../../Makefile.conf

FILES = $(shell echo makl_*)
FILES_DIR = "$(MAKL_ROOT)/cf/helpers"
FILES_MODE = 0444

include files.mk
