# $Id: Makefile,v 1.3 2006/12/10 13:19:47 tho Exp $

include common.mk
include ../Makefile.conf

FILES = $(shell echo makl*)
FILES_DIR = $(MAKL_ROOT)/cf
FILES_MODE = 0444

SUBDIR = helpers

include files.mk
include subdir.mk
