# $Id: Makefile,v 1.4 2008/11/07 20:00:50 tho Exp $

include common.mk
include ../Makefile.conf

FILES = $(shell echo makl*)
FILES_DIR = $(MAKL_ROOT)/cf
FILES_MODE = 0444

SUBDIR = helpers

include files.mk
include subdir.mk
