# $Id: Makefile,v 1.3 2008/11/07 20:00:50 tho Exp $

include common.mk
include ../Makefile.conf

FILES = dist.tmpl file.tmpl include.tmpl lib.tmpl man.tmpl prog.tmpl 
FILES += script.tmpl subdir.tmpl xeno.tmpl subst.tmpl
FILES_DIR = $(MAKL_ROOT)/tmpl
FILES_MODE = 0644

include files.mk
