# $Id: Makefile,v 1.1 2006/11/02 16:16:30 tat Exp $
# 
# Makefile for 3rd-party package dependencies

include common.mk
include ../Makefile.conf

PARTY_NAME = proggie-1.0.0

PARTY_NO_DOWN = true
PARTY_NO_CHK = true
PARTY_NO_INSTALL = true
PARTY_NO_CONF = true

include party.mk

test: all
